### ISSUE TITLE
Backup crashing app after restore

### ISSUE THREAD

**Issue by pdimu** [7heMech/InnerTune-Backup-Fix#1]
InnerTune crashes after restoring the solved backup
Will upload a record of the screen with the process and logs if I find

**Comment by 7heMech** [comment]
@pdimu yeah, and maybe check if you're on the latest versions of the apps.

**Comment by pdimu** [comment]
> @pdimu yeah, and maybe check if you're on the latest versions of the apps.

I am

**Comment by pdimu** [comment]
My phone crashed when using record you to record so imma use the native app

**Comment by pdimu** [comment]
My phone crashed when using record you to record so imma use the native app

**Comment by pdimu** [comment]
Some intrusive notifications, split in 2 videos cuz the first try to "convert" the backup didn't want to work but it's done
> Error while uploading Screenrecorder-2024-08-11-19-59-44-244.mp4

And the first one died as well

**Comment by 7heMech** [comment]
> Some intrusive notifications, split in 2 videos cuz the first try to "convert" the backup didn't want to work but it's done
> > Error while uploading Screenrecorder-2024-08-11-19-59-44-244.mp4
> 
> And the first one died as well
> 

Hmm, I tried with a new backup, are you sure you're using the right backup? It should be _fixed.backup

**Comment by pdimu** [comment]
Exported at 720p and cut some parts

https://github.com/user-attachments/assets/38e31942-72c4-4883-bb34-0cbdcf422083

https://github.com/user-attachments/assets/d87b38f6-d798-47b6-b2b8-42ba1be64285

**Comment by pdimu** [comment]
> > Some intrusive notifications, split in 2 videos cuz the first try to "convert" the backup didn't want to work but it's done
> > > Error while uploading Screenrecorder-2024-08-11-19-59-44-244.mp4
> > 
> > And the first one died as well
> > 
> 
> Hmm, I tried with a new backup, are you sure you're using the right backup? It should be _fixed.backup
> 

Yes I am (checked the file now)

**Comment by pdimu** [comment]
![Screenshot_2024-08-11-20-14-27-051-edit_org.fossify.filemanager.jpg](https://github.com/user-attachments/assets/d25caf3f-9a8f-4f6a-9904-c1cf2847fed9)

**Comment by Malopieds** [comment]
If you're not using google login, please provide the backup here

**Comment by pdimu** [comment]
> If you're not using google login, please provide the backup here

Unfortunately, I am using Google login

**Comment by 7heMech** [comment]
> > If you're not using google login, please provide the backup here
> 
> Unfortunately, I am using Google login

Maybe log out?

**Comment by pdimu** [comment]
What do I lose if I disconnect?

**Comment by pdimu** [comment]
> > > If you're not using google login, please provide the backup here
> > 
> > Unfortunately, I am using Google login
> 
> Maybe log out?

How? On the Content menu there's nothing mentioning logging out

**Comment by 7heMech** [comment]
Or just use - [aShell](https://f-droid.org/packages/in.sunilpaulmathew.ashell/) with [shizuku](https://play.google.com/store/apps/details?id=moe.shizuku.privileged.api) and write command `logcat --buffer=crash`

**Comment by pdimu** [comment]
> Or just use - [aShell](https://f-droid.org/packages/in.sunilpaulmathew.ashell/) with shizuku and write command `logcat --buffer=crash`

I don't have WiFi now

**Comment by 7heMech** [comment]
> > Or just use - [aShell](https://f-droid.org/packages/in.sunilpaulmathew.ashell/) with shizuku and write command `logcat --buffer=crash`
> 
> I don't have WiFi now

You can use shizuku in wireless debugging mode and then use aShell to- oh, you mean you can't install apps? These two apps are a total of 5MB, you decide, maybe you can do it later.

**Comment by 7heMech** [comment]
> How? On the Content menu there's nothing mentioning logging out

Kick the session from your google acc settings ig.

**Comment by pdimu** [comment]
> > > Or just use - [aShell](https://f-droid.org/packages/in.sunilpaulmathew.ashell/) with shizuku and write command `logcat --buffer=crash`
> > 
> > I don't have WiFi now
> 
> You can use shizuku in wireless debugging mode and then use aShell to- oh, you mean you can't install apps? These two apps are a total of 5MB, you decide, maybe you can do it later.

No, I have both apps. I'm not connected to WiFi and I can't use wireless debugging

**Comment by pdimu** [comment]
> > > > > If you're not using google login, please provide the backup here
> > > > 
> > > > Unfortunately, I am using Google login
> > > 
> > > Maybe log out?
> > 
> > How? On the Content menu there's nothing mentioning logging out
> 
> Kick the session from your google acc settings ig.
> 
> 

Aaaaaaaaaaaaaaaaaw

**Comment by 7heMech** [comment]
> No, I have both apps. I'm not connected to WiFi and I can't use wireless debugging 

Ooh, I see...

**Comment by Malopieds** [comment]
To logout click on content then your username, you will be redirected to ytm page. Logout from there (click on your logo and then logout as for ytm)

**Comment by pdimu** [comment]
> To logout click on content then your username, you will be redirected to ytm page. Logout from there (click on your logo and then logout as for ytm)

When doing that I need to login for some reason

**Comment by pdimu** [comment]
Apparently I can't upload the backup. Why, I don't know. Imma try to move the file to an image folder to see if GitHub accepts it. Otherwise, I'm going to compress it in zip

**Comment by 7heMech** [comment]
@pdimu maybe - https://www.file.io/

**Comment by pdimu** [comment]
> @pdimu maybe - https://www.file.io/
 
Thanks for the tip, @7heMech!

https://file.io/H7zkoyTuxZvq

**Comment by 7heMech** [comment]
Umm, @pdimu are you sure you are importing the fix in the original app, because I imported fix of your backup successfully...

**Comment by pdimu** [comment]
> Umm, @pdimu are you sure you are importing the fix in the original app, because I imported fix of your backup successfully...

Then I guess it's just my phone's performance.

Also, the music you've seen in the feed was never real

**Comment by 7heMech** [comment]
> Also, the music you've seen in the feed was never real

I never looked at it. But that's strange can you explain the behavior you're getting is the app crashing?

**Comment by pdimu** [comment]
> I never looked at it. But that's strange can you explain the behavior you're getting is the app crashing?

After selecting the backup and returning to InnerTune, it shuts off the app with a black screen and it kicks me out in the launcher

I did some brain-storm and I decided to try the process of restoring again, but this time with the backup ready and no apps running. Unsurprisingly, it worked.

So now I know it was because of my phone

**Comment by 7heMech** [comment]
Awesome, I suppose I can close this now, if you ever get logs of crash and wish to give for further review feel free to open.

**Comment by pdimu** [comment]
> Awesome, I suppose I can close this now, if you ever get logs of crash and wish to give for further review feel free to open.

I think it's "fixed", altought it was a hardware issue. You should change the state to not planned
